package/uclibc: enable long double math for xtensa
It fixes the following build failure for packages that expect long
double support in libm:

  Linking C executable winpr-hash
  ../../libwinpr/utils/libwinpr-utils.so.0.1.0: undefined reference to `powl'
  ../../libwinpr/utils/libwinpr-utils.so.0.1.0: undefined reference to `fmodl'
  ../../libwinpr/utils/libwinpr-utils.so.0.1.0: undefined reference to `ceill'
  ../../libwinpr/utils/libwinpr-utils.so.0.1.0: undefined reference to `log10l'
  ../../libwinpr/utils/libwinpr-utils.so.0.1.0: undefined reference to `floorl'

Fixes:
  http://autobuild.buildroot.net/results/323/3236ddfe8eaf89f05f84db60eb42583cca397464/

Mainline status: patch submitted.

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>