trousers: remove inline for read_data/write_data
read_data and write_data functions are declared with inline, but
their definition is not in a .h file. This is causing errors when
linking:

tcsps.c:(.text+0x4ac): undefined reference to `read_data'
tcsps.c:(.text+0x1888): undefined reference to `write_data'
...

The patch is a partial backport of upstream commit
3297fcdf5ac0df868778e976b8b59e35542c1ee2.

Fixes:
http://autobuild.buildroot.net/results/1a53d929bcec840cd18185e54b1a6da8aa849269/
http://autobuild.buildroot.net/results/fad66e88b5a97004b21658d413f4d3a6d0d8838b/
http://autobuild.buildroot.net/results/c7e23b8ec2c69798482868e18311ebf2c01b65e0/
...

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>