dropwatch: Remove -Werror from CFLAGS
-Werror shouldn't be used in released code since it can
cause random build failures on moderate warnings. It also
depends on the used toolchain since different toolchains may
or may not print the same warnings.

Fixes the following build problem on MIPS64/n64:

main.c: In function handle_dm_alert_msg:
main.c:336:5: error: format %llx expects argument of
type long long unsigned int, but argument 4 has
type __u64 [-Werror=format=]

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>