libgtk3: fix undefined reference to get_xkb()
When configuring Gtk+ with --disable-xkb, the build fails because of an
undefined reference to get_xkb().

This issue as been reported upstream [1]. This patch fixes it.

Fixes:

http://autobuild.buildroot.net/results/513/513d79b97bb8ad0e5cd431c47c706b5ec87a9882/
http://autobuild.buildroot.net/results/0c3/0c3f1df92481852622445478d2239371fc818f41/

[1] https://bugzilla.gnome.org/show_bug.cgi?id=739070

Signed-off-by: Eric Le Bihan <eric.le.bihan.dev@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>