wireshark: fix inet_pton detection
Patch configure.ac to not assume broken inet_pton in case of cross
compiling (avoids double definition), similare patch is used
for OpenEmbedded (see [1]).

Fixes [2]:

  host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libc.a(ntop.os): In function `inet_pton':
  ntop.c:(.text+0x4b4): multiple definition of `inet_pton'
  wsutil/.libs/libwsutil.a(inet_pton.o):inet_pton.c:(.text+0xe0): first defined here
  collect2: error: ld returned 1 exit status

[1] http://cgit.openembedded.org/openembedded/tree/recipes/wireshark/files/fix-configure.patch
[2] http://autobuild.buildroot.net/results/b35/b354ba668ca9476c143f5f7ef1b727b0b5672b04

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>