libvips: requires C++ support
libvips requires C++ support, otherwise it will fail with an error
message like this one:

error: ../libvips/.libs/libvips.so: No such file or directory

The '--disable-cxx' configure option seems to be broken, so in the
meantime a compiler with C++ support is required in order to build
libvips successfully.

Reported upstream:

  https://github.com/jcupitt/libvips/issues/231

Fixes:

  http://autobuild.buildroot.net/results/cdc7cf5d3501f80c74b70aa09f93b2ad4e2f8602/
  http://autobuild.buildroot.net/results/39173dbcbbd0a243900ea583cec024b51f8b803a/
  http://autobuild.buildroot.net/results/6794705195bcdb636a8e6582ef5a1e153d4d66b3/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>