atngw100_defconfig: update to fix build failure
atngw100_defconfig: update to fix build failure:

  * The AVR32 toolchain fails to build with the new uClibc version
    0.9.31.x. Use the older uClibc 0.9.30.x branch instead.
  * Disable linux-fusion as it fails to build
    (why was this selected anyway, when DirectFB was not selected?).
  * U-Boot 2010.03 is broken for AVR32. The build fails with:
      zlib.c:31:27: error: asm/unaligned.h: No such file or directory
    Select the older U-Boot 2009.08 version that builds instead.
  * Disable rsync as it fails to build.

Build tested with 'make distclean && make atngw100_defconfig && make'
on an Ubuntu 10.04 x86_64 host.

Signed-off-by: Bjørn Forsman <bjorn.forsman@gmail.com>
Acked-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>