minidlna: Fix automagic dependency to libiconv
minidlna will detect and use the libiconv library if
the package is selected. In that case, we need to link
against -liconv.

Fixes the following linking problem:

tagutils/tagutils.o: In function `do_iconv.constprop.6':
tagutils.c:(.text+0x4d5c): undefined reference to `libiconv_open'
tagutils.c:(.text+0x4da0): undefined reference to `libiconv'
tagutils.c:(.text+0x4e08): undefined reference to `libiconv_close'

[Peter: wrap COMMON_LIBS line]
Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>