libpfm4: needs NPTL support
Fixes following build failure:
--->---
self_smpl_multi.c: In function 'my_thread':
self_smpl_multi.c:354:2: error: implicit declaration of function 'pthread_barrier_wait' [-Werror=implicit-function-declaration]
  pthread_barrier_wait(&barrier);
  ^
self_smpl_multi.c: In function 'main':
self_smpl_multi.c:450:2: error: implicit declaration of function 'pthread_barrier_init' [-Werror=implicit-function-declaration]
  pthread_barrier_init(&barrier, 0, max_thr+1);
  ^
cc1: all warnings being treated as errors
--->---

And since xtensa, avr32 and bfin don't support NPTL we may remove arch
dependencies as well.

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>

Cc: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Cc: Peter Korsgaard <peter@korsgaard.com>
Cc: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>