xapp_xdm: depends on MMU
Fixes http://sysmic.org/~jezz/results/e891eb7e:

dm.o: In function `_StartDisplay':
dm.c:(.text+0xd6e): undefined reference to `_fork'
server.o: In function `_StartServerOnce':
server.c:(.text+0x266): undefined reference to `_fork'
session.o: In function `_runAndWait':
session.c:(.text+0x67a): undefined reference to `_fork'
session.o: In function `_ManageSession':
session.c:(.text+0xa2a): undefined reference to `_fork'
collect2: ld returned 1 exit status

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>