fbterm: fix musl compile (missing string.h include)
Fixes [1]:

  mouse.cpp: In function 's32 open_gpm(Gpm_Connect*)':
  mouse.cpp:58:37: error: 'memset' was not declared in this scope
    memset((s8 *)&addr, 0, sizeof(addr));
                                     ^
  mouse.cpp:60:64: error: 'strncpy' was not declared in this scope
    strncpy(addr.sun_path, GPM_NODE_CTL, sizeof(addr.sun_path) - 1);

in case BR2_PACKAGE_GPM is defined.

Add proper gpm dependency and configure option too.

[1] http://autobuild.buildroot.net/results/a60/a602d61e68f662217ad868de79711a8ea892a3a9

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>